name = "AutoFeatures"
uuid = "35d802a2-66f1-4f55-8b76-04aa3700b885"
authors = ["evalparse <zhuojia.dai@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
